# Update Checker Settings
update-checker:
  enable: true
  console: true # Post message to console
  op: true # Send update notification to opped players on join

# Language, specify the language file to use, for example `en_US` which will load `/lang/en_US.json`
language: "en_US"

# Lance Settings
lance:
  itemIdList:
    - "nexo:copper_lance"
    - "nexo:iron_lance"
    - "nexo:gold_lance"
    - "nexo:steel_lance"
    - "nexo:diamond_lance"
    - "nexo:netherite_lance"
    - "nexo:copper_pike"
    - "nexo:iron_pike"
    - "nexo:gold_pike"
    - "nexo:steel_pike"
    - "nexo:diamond_pike"
    - "nexo:netherite_pike"

# Combat Settings
combat:
  maxDamage: 10.0
  mobDamageMultiplier: 1.5
  knockoffThreshold: 50
  footDamage: 0.5
  footDamageMobs: 1.0
  slownessDuration: 100
  slownessLevel: 1

sounds:
  hit: "ENTITY_SLIME_ATTACK"

towny:
  enabled: true
  # Whether mobs in towns should be protected
  protectMobs: true

momentum:
  movementThreshold: 0.05
  stallTimeMs: 500
  maxDecayRate: 20
  turnThreshold: 30.0
  turnLoss: 10.0
  straightGain: 1

# Display settings
display:
  useActionBar: true         # Whether to show momentum on the action bar
  actionBarFormat: "&bMomentum: %momentum%/100"

# Visual effects settings
effects:
  showTurnEffects: true     # Show particles and play sounds on turns
  showStopEffects: true     # Show particles and play sounds when stopping
