# Update Checker Settings
update-checker:
  enable: true
  console: true # Post message to console
  op: true # Send update notification to opped players on join

# Language, specify the language file to use, for example `en_US` which will load `/lang/en_US.json`
language: "en_US"

# Lance Settings
lance:
  itemIdList:
    - "copper_lance"
    - "iron_lance"
    - "gold_lance"
    - "steel_lance"
    - "diamond_lance"
    - "netherite_lance"
    - "copper_pike"
    - "iron_pike"
    - "gold_pike"
    - "steel_pike"
    - "diamond_pike"
    - "netherite_pike"

# Combat Settings
combat:
  mobDamageMultiplier: 1.5
  knockoffThreshold: 50
  knockoffChance: 0.33
  footDamage: 1.0
  footDamageMobs: 1.0
  slownessDuration: 100
  slownessLevel: 1

sounds:
  hit: "minecraft:entity.slime.attack"

towny:
  enabled: true
  # Whether mobs in towns should be protected
  protectMobs: true

momentum:
  movementThreshold: 1.25
  stallTimeMs: 500
  maxDecayRate: 20
  turnThreshold: 50.0
  turnLoss: 20.0
  straightGain: 2
  momentumDamageMultiplier:
    momentum_100: 2.5
    momentum_75-99: 2
    momentum_50-74: 1.5
    momentum_25-49: 1
    momentum_0-24: 0.5

# Display settings
display:
  actionBarFormat: "<aqua>Momentum: %momentum%/100"

# Visual effects settings
effects:
  showTurnEffects: true     # Show particles and play sounds on turns
  showStopEffects: true     # Show particles and play sounds when stopping
