# ----- LANCE ITEM SETTINGS -----
lance:
  # Options include: VANILLA, ITEMSADDER, ORAXEN, NEXO and MMOITEMS
  # An item provider plugin is recommended such as Nexo !!
  itemProvider: "VANILLA"
  # This section only applies if the "itemProvider" is NOT "VANILLA", using an item plugin
  itemPluginIDList:
    - "iron_lance"
    - "gold_lance"
    - "diamond_lance"
    - "netherite_lance"
  # This section only applies if the "itemProvider" is set to "VANILLA"
  defaultLanceItems:
    - name: "iron_lance"
      material: IRON_SWORD
      customModelData: 8693
      displayName: "<gray><b>Iron Lance"
      lore:
        - "<yellow>A special weapon used in horse combat"
    - name: "gold_lance"
      material: GOLDEN_SWORD
      customModelData: 8694
      displayName: "<yellow><b>Golden Lance"
      lore:
        - "<yellow>A special weapon used in horse combat"
    - name: "diamond_lance"
      displayName: "<dark_aqua><b>Diamond Lance"
      lore:
        - "<yellow>A special weapon used in horse combat"
    - name: "netherite_lance"
      material: NETHERITE_SWORD
      customModelData: 8696
      displayName: "<dark_gray><b>Netherite Lance"
      lore:
        - "<yellow>A special weapon used in horse combat"

# ----- COMBAT SETTINGS -----
momentum:
  movementThreshold: 1.25
  stallTimeMs: 500
  maxDecayRate: 20
  turnThreshold: 50.0
  turnLoss: 15.0
  straightGain: 2
  momentumDamageMultiplier:
    momentum_100: 2.5
    momentum_75-99: 2
    momentum_50-74: 1.5
    momentum_25-49: 1
    momentum_0-24: 0.5

combat:
  playerDamageMultiplier: 1.5
  mobDamageMultiplier: 1.5
  knockoffThreshold: 50
  knockoffChance: 0.2

# ----- SOUND SETTINGS -----
sounds:
  hit:
    enabled: true
    effect: "minecraft:entity.zombie.attack_iron_door"
    volume: 0.5
    pitch: 1.0

# ----- DISPLAY SETTINGS -----
display:
  actionBarFormat: "<aqua>Momentum: %momentum%/100"

# ----- HOOKS & COMPATIBILITY -----

# This allows for compatibility with Towny
# Enabling this prevents horse combat against mobs protected in Town claims
towny:
  enabled: true