# Update Checker Settings
update-checker:
  enable: false
  console: false # Post message to console
  op: false # Send update notification to opped players on join

# Language, specify the language file to use, for example `en_US` which will load `/lang/en_US.json`
language: "en_US"

# Lance Settings
lance:
  itemIdList:
    - "copper_lance"
    - "iron_lance"
    - "gold_lance"
    - "steel_lance"
    - "diamond_lance"
    - "netherite_lance"
    - "copper_pike"
    - "iron_pike"
    - "gold_pike"
    - "steel_pike"
    - "diamond_pike"
    - "netherite_pike"

# Combat Settings
combat:
  playerDamageMultiplier: 1.5
  mobDamageMultiplier: 1.5
  knockoffThreshold: 50
  knockoffChance: 0.2

sounds:
  hit:
    enabled: true
    effect: "minecraft:entity.zombie.attack_iron_door"
    volume: 0.5
    pitch: 1.0

towny:
  enabled: true
  # Whether mobs in towns should be protected
  protectMobs: true

momentum:
  movementThreshold: 1.25
  stallTimeMs: 500
  maxDecayRate: 20
  turnThreshold: 50.0
  turnLoss: 15.0
  straightGain: 2
  momentumDamageMultiplier:
    momentum_100: 2.5
    momentum_75-99: 2
    momentum_50-74: 1.5
    momentum_25-49: 1
    momentum_0-24: 0.5

# Display settings
display:
  actionBarFormat: "<aqua>Momentum: %momentum%/100"

# Visual effects settings
effects:
  showTurnEffects: false     # Show particles and play sounds on turns
  showStopEffects: false     # Show particles and play sounds when stopping
